/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_pict_PictJni */

#ifndef _Included_com_microsoft_pict_PictJni
#define _Included_com_microsoft_pict_PictJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    createTask
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_createTask
  (JNIEnv *, jobject);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    deleteTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_pict_PictJni_deleteTask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    createModel
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_createModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    deleteModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_pict_PictJni_deleteModel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    setRootModel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_pict_PictJni_setRootModel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    addParameter
 * Signature: (JJI[I)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_addParameter
  (JNIEnv *, jobject, jlong, jlong, jint, jintArray);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    attachChildModel
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_pict_PictJni_attachChildModel
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    addExclusion
 * Signature: (J[J[J)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_pict_PictJni_addExclusion
  (JNIEnv *, jobject, jlong, jlongArray, jlongArray);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    addSeed
 * Signature: (J[J[J)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_pict_PictJni_addSeed
  (JNIEnv *, jobject, jlong, jlongArray, jlongArray);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    generate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microsoft_pict_PictJni_generate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    allocateResultBuffer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_allocateResultBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    freeResultBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_pict_PictJni_freeResultBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    resetResultFetching
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_microsoft_pict_PictJni_resetResultFetching
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    getNextResultRow
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_getNextResultRow
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     com_microsoft_pict_PictJni
 * Method:    getTotalParameterCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_microsoft_pict_PictJni_getTotalParameterCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
